name: Update tested solc versions

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: npm
    - run: |
        set -euo pipefail
        all_versions() {
          npm view --json solc | jq -r '.versions[]'
        }
        exclude_unwanted() {
          grep -v -e - -e '^0\.[0-6]' | grep -vF -e 0.8.1 -e 0.8.7 -e 0.8.14
        }
        npm install -DE $(all_versions | exclude_unwanted | sed 's/\S*/solc-&@npm:solc@&/')
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.PR_PAT }}
        branch: update-solc
        title: Update solc
        body: |
          - [ ] Review the [latest Solidity changes](https://github.com/ethereum/solidity/blob/develop/Changelog.md) and add test files for any new language constructs.
          - [ ] If tests are failing: fix the schema and update the changelog accordingly.
