name: Update tested solc versions

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: npm
    - run: |
        npm install -DE $(npm view --json solc | jq -r '.versions[] | select(test("0[.]([7-9]|1[0-9]+)[.]|1[0-9]*[.][0-9]+[.]") and (contains("-") | not)) | "solc-" + . + "@npm:solc@" + .')
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        branch: update-solc
        title: Update solc
